INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (10920,'Aliens','https://m.media-amazon.com/images/I/91TYB8gep+L.jpg',8.2,1986,'Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony, but finds herself battling the Alien Queen and her offspring.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (17173,'Animal House','https://m.media-amazon.com/images/M/MV5BM2M2ZDA4MTYtOGRjMi00OTg5LWI1ZTUtMjQxZTc2NWZjNDFkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',7.5,1978, 'At a 1962 college, Dean Vernon Wormer is determined to expel the entire Delta Tau Chi Fraternity, but those troublemakers have other plans for him.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (18979,'Apollo 13','https://m.media-amazon.com/images/M/MV5BMjc4MzZlNmQtN2ZlOS00OGQzLWI5YjEtNDQ2YmZlN2FjNTIxXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',7.5,1995,'NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage putting the lives of the three astronauts on board in jeopardy.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (30959,'Batman Begins','https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',8.3,2005,'After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (46169,'Braveheart','https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',8.3,1995,'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (109093,'Fargo','https://m.media-amazon.com/images/M/MV5BNDJiZDgyZjctYmRjMS00ZjdkLTkwMTEtNGU1NDg3NDQ0Yzk1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',8.2,1996,'Various chronicles of deception, intrigue and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back one way or another to Fargo, North Dakota.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (111813,'Few Good Men','https://m.media-amazon.com/images/M/MV5BMmRlZDQ1MmUtMzE2Yi00YTkxLTk1MGMtYmIyYWQwODcxYzRlXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_FMjpg_UX1000_.jpg',7.5,1992,'Military lawyer Lieutenant Daniel Kaffee defends Marines accused of murder. They contend they were acting under orders.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (112290,'Fight Club','https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg',8.5,1999,'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (116907,'Footloose','https://m.media-amazon.com/images/M/MV5BMTY3MjIzMjk4M15BMl5BanBnXkFtZTcwMzMxMzIzNg@@._V1_FMjpg_UX1000_.jpg',5.8,1984,'City teenager Ren MacCormack moves to a small town where rock music and dancing have been banned, and his rebellious spirit shakes up the populace.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (124110,'Garden State','https://m.media-amazon.com/images/M/MV5BMjc5MDE0NjkxOF5BMl5BanBnXkFtZTcwNzA0NTkyMw@@._V1_.jpg',8.3,2004,'A quietly troubled young man returns home for his mother''s funeral after being estranged from his family for a decade.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (130128,'Godfather, The','https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',9,1972,'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (147603,'Hollow Man','https://m.media-amazon.com/images/M/MV5BMmFjMzY0ZjgtMjZhOC00MTRlLWEyM2EtYjBhOGVlMTQ0MTgzXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_FMjpg_UX1000_.jpg',5.3,2000,'A brilliant scientist''s discovery renders him invisible, but transforms him into an omnipotent, dangerous megalomaniac.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (167324,'JFK','https://m.media-amazon.com/images/M/MV5BYjYyODExMDctZjgwYy00ZjQwLWI4OWYtOGFlYjA4ZjEzNmY1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg',7.8,1991,'New Orleans District Attorney Jim Garrison discovers there''s more to the Kennedy assassination than the official story.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (176711,'Kill Bill: Vol. 1','https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',8.4,2003,'After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (176712,'Kill Bill: Vol. 2','https://m.media-amazon.com/images/M/MV5BNmFiYmJmN2QtNWQwMi00MzliLThiOWMtZjQxNGRhZTQ1MjgyXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_FMjpg_UX1000_.jpg',8.2,2004,'The Bride continues her quest of vengeance against her former boss and lover Bill, the reclusive bouncer Budd, and the treacherous, one-eyed Elle.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (192017,'Little Mermaid, The','https://m.media-amazon.com/images/M/MV5BN2JlZTBhYTEtZDE3OC00NTA3LTk5NTQtNjg5M2RjODllM2M0XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_FMjpg_UX1000_.jpg',7.3,1989,'A young mermaid makes a deal with a sea witch, to trade her beautiful voice for human legs so she can discover the world above water and impress a prince.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (194874,'Lost in Translation','https://m.media-amazon.com/images/M/MV5BMTc3OTMzMDkxNF5BMl5BanBnXkFtZTcwNzIxNTAwMQ@@._V1_.jpg',8,2003,'A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (207992,'Matrix, The','https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',8.5,1999,'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (210511,'Memento','https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',8.7,2000,'A man with short-term memory loss attempts to track down his wife''s murderer.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (224842,'Mystic River','https://m.media-amazon.com/images/M/MV5BMTIzNDUyMjA4MV5BMl5BanBnXkFtZTYwNDc4ODM3._V1_FMjpg_UX1000_.jpg',8.1,2003,'The lives of three men who were childhood friends are shattered when one of them has a family tragedy.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (237431,'O Brother, Where Art Thou?','https://m.media-amazon.com/images/M/MV5BMjZkOTdmMWItOTkyNy00MDdjLTlhNTQtYzU3MzdhZjA0ZDEyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',7.8,2000,'In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (238072,'Oceanâ€s Eleven','https://m.media-amazon.com/images/M/MV5BYzVmYzVkMmUtOGRhMi00MTNmLThlMmUtZTljYjlkMjNkMjJkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_FMjpg_UX1000_.jpg',7.5,2001,'Danny Ocean gathers a group of his World War II compatriots to pull off the ultimate Las Vegas heist. Together the eleven friends plan to rob five Las Vegas casinos in one night.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (238695,'Office Space','https://m.media-amazon.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_FMjpg_UX1000_.jpg',7.6,1999,'Three company workers who hate their jobs decide to rebel against their greedy boss.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (254943,'Pi','https://m.media-amazon.com/images/M/MV5BMTk3MThhNGEtY2E4NS00MWMwLTg4MzQtMTk4ZTcwYzRlNDNiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',7.5,1998,'A paranoid mathematician searches for a key number that will unlock the universal patterns found in nature.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (256630,'Pirates of the Caribbean','https://m.media-amazon.com/images/M/MV5BNGYyZGM5MGMtYTY2Ni00M2Y1LWIzNjQtYWUzM2VlNGVhMDNhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',8.7,2003,'Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save his love, the governor''s daughter, from Jack''s former pirate allies, who are now undead.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (257264,'Planes, Trains & Automobiles','https://m.media-amazon.com/images/M/MV5BMjAwODc5NzYzOF5BMl5BanBnXkFtZTcwNTk4MjEzOQ@@._V1_FMjpg_UX1000_.jpg',7.2,1987,'A Chicago advertising man must struggle to travel home from New York for Thanksgiving, with a lovable oaf of a shower-curtain-ring salesman as his only companion.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (267038,'Pulp Fiction','https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',8.7,1994,'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (276217,'Reservoir Dogs','https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',8.3,1992,'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (297838,'Shawshank Redemption, The','https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',9,1994,'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (300229,'Shrek','https://m.media-amazon.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',8.1,2001,'A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (306032,'Snatch.','https://m.media-amazon.com/images/M/MV5BMTA2NDYxOGYtYjU1Mi00Y2QzLTgxMTQtMWI1MGI0ZGQ5MmU4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',7.9,2000,'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (313459,'Star Wars','https://m.media-amazon.com/images/M/MV5BMDljNTQ5ODItZmQwMy00M2ExLTljOTQtZTVjNGE2NTg0NGIxXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_FMjpg_UX1000_.jpg',8.8,1977,'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (314965,'Stir of Echoes','https://m.media-amazon.com/images/M/MV5BMjE2NTEwZWYtYzcxYi00MzZhLTg0NDMtNTBhMTM3MjEyMmU3XkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_FMjpg_UX1000_.jpg',7,1999,'After being hypnotized by his sister-in-law, a man begins seeing haunting visions of a girl''s ghost and a mystery begins to unfold around him.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (333856,'Titanic','https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',6.9,1997,'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (344203,'UHF','https://m.media-amazon.com/images/M/MV5BMGQ5ZjRiYzctYzA3Yy00NjQwLTgyMTgtZTJkNzBiN2E0MmExXkEyXkFqcGdeQXVyMTIwMjk5NTky._V1_FMjpg_UX1000_.jpg',6.6,1989, 'An unemployed visionary becomes the manager of a local television station. The station becomes a success, with all sorts of hilarious sight gags and wacky humor.');
INSERT INTO Movies(ID,MOVIE_NAME,POSTER,RANK,RELEASE_DATE,DESCRIPTION) VALUES  (350424,'Vanilla Sky','https://m.media-amazon.com/images/M/MV5BYzFlMTJjYzUtMWFjYy00NjkyLTg1Y2EtYmZkMjdlOGQ1ZGYwL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',6.9,2001,'A self-indulgent and vain publishing magnate finds his privileged life upended after a vehicular accident with a resentful lover.');


INSERT INTO Genres(ID,GENRE) VALUES(1,'Sci-Fi');
INSERT INTO Genres(ID,GENRE) VALUES(2,'Action');
INSERT INTO Genres(ID,GENRE) VALUES(3,'Thriller');
INSERT INTO Genres(ID,GENRE) VALUES(4,'Horror');
INSERT INTO Genres(ID,GENRE) VALUES(5,'Family');
INSERT INTO Genres(ID,GENRE) VALUES(6,'Comedy');
INSERT INTO Genres(ID,GENRE) VALUES(7,'Drama');
INSERT INTO Genres(ID,GENRE) VALUES(8,'Animation');
INSERT INTO Genres(ID,GENRE) VALUES(9,'Crime');
INSERT INTO Genres(ID,GENRE) VALUES(10,'Fantasy');
INSERT INTO Genres(ID,GENRE) VALUES(11,'Adventure');
INSERT INTO Genres(ID,GENRE) VALUES(12,'War');
INSERT INTO Genres(ID,GENRE) VALUES(13,'Mystery');
INSERT INTO Genres(ID,GENRE) VALUES(14,'Music');
INSERT INTO Genres(ID,GENRE) VALUES(15,'Romance');





INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID) VALUES  (10920,1);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID) VALUES                                 (10920,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID) VALUES                               (10920,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID) VALUES                                (10920,4);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID) VALUES                                (17173,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (18979,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (30959,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (30959,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (30959,10);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (30959,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (30959,11);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (46169,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (46169,12);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (46169,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (109093,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (109093,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (109093,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (111813,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (111813,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (112290,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (112290,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (112290,13
);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (112290,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (116907,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (116907,5);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (116907,14);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (124110,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (124110,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (130128,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (130128,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (147603,4);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (147603,1);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (147603,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (167324,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (167324,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (167324,13
);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (167324,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (176711,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (176711,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (176711,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (176712,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (176712,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (176712,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (176712,15);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (192017,5);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (192017,8);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (192017,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (192017,14);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (192017,15);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (192017,10);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (194874,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (194874,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (207992,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (207992,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                 (207992,1);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (210511,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (210511,13);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (210511,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (224842,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (224842,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (224842,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (237431,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (237431,11);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (237431,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (238072,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (238072,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                                (238072,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (238695,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (254943,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (254943,1);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (256630,11);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                               (256630,10);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (257264,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (267038,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (267038,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (276217,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (276217,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (276217,13);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (276217,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (297838,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (300229,11);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (300229,15);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (300229,8);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                              (300229,10);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (300229,5);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (300229,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (306032,9);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                             (306032,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (313459,1);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (313459,2);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (313459,11);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (313459,10);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                            (314965,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                           (314965,4);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                           (314965,13);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                          (333856,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                          (333856,15);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                          (344203,6);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                         (350424,7);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES                          (350424,15);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES  (350424,1);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES (350424,3);
INSERT INTO movies_genres (MOVIES2_ID,GENRES_ID)VALUES (350424,13
);